# Generated by Django 3.2 on 2021-04-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisme',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organisme',
            name='last_name',
        ),
    ]
