# Generated by Django 3.2 on 2021-04-17 04:43

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.category'),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='name',
            field=models.CharField(help_text='Fill name and username will get prefilled with no spaces.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and no spaces! fill name and let this field get prefilled.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
