# Generated by Django 3.2 on 2021-04-17 05:06

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210417_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='email',
            field=models.EmailField(help_text='You must fill this void to send the email with the random password.', max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.category')),
            ],
        ),
    ]
