# Generated by Django 3.2 on 2021-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210417_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, help_text="Check this field to create an account with this model's data."),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='name',
            field=models.CharField(help_text='Fill name and username will get prefilled with no spaces.', max_length=30, null=True),
        ),
    ]
