# Generated by Django 3.2 on 2021-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210417_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='function',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
