# Generated by Django 3.2 on 2021-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_entity_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='organisme',
            options={'verbose_name': 'Organism', 'verbose_name_plural': 'Organisms'},
        ),
        migrations.RemoveField(
            model_name='organisme',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='organisme',
            name='user_permissions',
        ),
    ]
