# Generated by Django 3.2 on 2021-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='odience',
            field=models.CharField(choices=[('Define Later', 'Define Later'), ('Private', 'Private'), ('Public', 'Public')], default='Define Later', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Brouillon', 'Brouillon')], default='Brouillon', max_length=60),
        ),
    ]
