# Generated by Django 3.2 on 2021-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210418_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Brouillon', 'Brouillon')], default='Brouillon', max_length=60),
        ),
    ]
