# Generated by Django 3.2 on 2021-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210421_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisme',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
