# Generated by Django 3.2 on 2021-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_organisme_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='object',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
